### ISSUE TITLE
Most modules are missing in CSharp-Language-Integrated-Query-StartingSamples.zip

### ISSUE THREAD

**Issue by aaronfranke** [PaulDSheriff/Pluralsight-Samples#1]
I downloaded this file from this repository as per the instructions on Pluralsight for the C# Language-Integrated Query (LINQ) course. However, there are only 2 folders/solutions in this ZIP, called "Module02" (which is actually for Module 3) and "Module05". There are no folders for Modules 4, 6, 7, 8, 9, 10, 11. For Module 4 I just wrote out all of the methods and regions manually in "Module02", but I don't think this was the intention, so I'm opening this bug report.

**Comment by PaulDSheriff** [comment]
Hi Aaron,

This file here is just for starting and if you want to type things in along with me in the video. For the completed files, you simply need to download them from the Exercise Files tab in Pluralsight. In that ZIP file you will find both start and finished samples.

Paul
